### ISSUE TITLE
约束未满足: !!whereis -a <ID>

### ISSUE THREAD

**Issue by xrh0905** [Lazy-Bing-Server/WhereIs-MCDR#1]
-s也用不了
两个名单都是空的

**Comment by Ra1ny-Yuki** [comment]
迟回抱歉。请提供您的完整配置文件和您使用该指令时的权限等级

**Comment by Ra1ny-Yuki** [comment]
此外，请先确认执行该指令者权限等级大于配置文件中`permission_requirements` - `admin`项的数值，由于`-a`（即**查询并广播他人坐标而非仅查询并显示给查询者**）和`-s`（即**查询受黑白名单保护的玩家**）可能在部分服务器属于侵犯隐私行为，故均需要`admin`权限

**Comment by xrh0905** [comment]
好的
权限等级 Owner(4)
配置文件:
`{
    "enable_here": true,
    "enable_where_is": true,
    "command_prefix": {
        "where_is": [
            "!!vris",
            "!!whereis",
            "!!where"
        ],
        "here": [
            "!!here"
        ]
    },
    "permission_requirements": {
        "where_is": 1,
        "here": 0,
        "admin": 3
    },
    "highlight_time": {
        "where_is": 30,
        "here": 60
    },
    "display_waypoints": {
        "voxelmap": true,
        "xaeros_minimap": true
    },
    "query_timeout": 3,
    "click_to_teleport": true,
    "location_protection": {
        "enable_whitelist": false,
        "enable_blacklist": true,
        "whitelist": [],
        "blacklist": [],
        "protected_text": {
            "en_us": "He/She's in your heart!",
            "zh_cn": "Ta在你心里!"
        }
    },
    "dimension_translation_mode": "minecraft",
    "custom_dimension_name": {
        "en_us": {
            "overworld": "Overworld",
            "the_nether": "Nether",
            "the_end": "The End"
        },
        "zh_cn": {
            "overworld": "主世界",
            "the_nether": "下界",
            "the_end": "末地"
        }
    }
}`

**Comment by Ra1ny-Yuki** [comment]
请再次确认指令正确，指令树注册的是`!!whereis <ID> -a`而非`!!whereis -a <ID>`

由于MCDR提供的插件指令树API并不便于各参数调换位置，因而实现额外参数和玩家ID之间的对换是一个极其麻烦且必要性不大的特性，本插件并未予以实现。

**Comment by Ra1ny-Yuki** [comment]
若可确认是指令语法有误，可否烦请确认本仓库的文档是否造成了误导，万分感谢

**Comment by xrh0905** [comment]
确认指令语法有误
我去看看文档
