### ISSUE TITLE
查询玩家时报错

### ISSUE THREAD

**Issue by CleMooling** [Lazy-Bing-Server/WhereIs-MCDR#2]
服务端：LeavesMC（Paper下游魔改端）
版本：1.20.1
报错内容：（命令为!!whereis ny666ny）
[MCDR] [08:26:27] [WhereIs_Main/DEBUG] [where_is]: ['VisceralCarp986\x1b[38;5;7m', 'Robert7735\x1b[38;5;7m', 'CleMooling\x1b[38;5;7m', 'ny666ny']
[Server] [08:26:27 INFO]: ny666ny has the following entity data: [-1.4746515d, -45.8194d, -53.436165d]
[MCDR] [08:26:27] [WhereIs_Main/ERROR] [minecraft_data_api]: [Minecraft Data API] Fail to Convert data "ny666ny has the following entity data: [-1.4746515": Expecting value: line 1 column 86 (char 85)
[MCDR] [08:26:27] [WhereIs_Main/ERROR] [where_is]: Unexpected exception occurred while querying player location
Traceback (most recent call last):
  File "plugins/WhereIs-v2.0.2+build.6.mcdr/where_is/entry.py", line 21, in where_is
    coordinate = get_player_coordinate(target_player, timeout=config.query_timeout)
  File "plugins/MinecraftDataAPI-v1.4.1.mcdr/minecraft_data_api/__init__.py", line 67, in get_player_coordinate
    raise ValueError('Fail to query the coordinate of player {}'.format(player))
ValueError: Fail to query the coordinate of player ny666ny

**Comment by xrh0905** [comment]
下游魔改端数据输出格式不对
