### ISSUE TITLE
高版本翻译错误

### ISSUE THREAD

**Issue by Adogs1** [Lazy-Bing-Server/WhereIs-MCDR#3]
这个错误在Fallen的here和地标(!!log)就存在
![QQ截图20240720152627](https://github.com/user-attachments/assets/066fd04d-cb4d-4cae-b8e8-83f9f78b025e)
createWorld.customize.preset.overworld应该更改为flat_world_preset.minecraft.overworld
参考：https://github.com/TISUnion/Here/issues/26

**Comment by AnzhiZhang** [comment]
配置文件看都不看呗
https://github.com/Lazy-Bing-Server/WhereIs-MCDR#config-file
