### ISSUE TITLE
Players who join with geysermc cannot use!!here,!!whereis, etc.

### ISSUE THREAD

**Issue by Seungmin922** [Lazy-Bing-Server/WhereIs-MCDR#4]
用geysermc加入的玩家,无法使用!!here、!!whereis等等
[latest.log](https://github.com/user-attachments/files/16622211/latest.log)

**Comment by Ra1ny-Yuki** [comment]
![image](https://github.com/user-attachments/assets/c2760b09-50c0-4316-b836-dac328448965)

需要服务端日志，客户端日志除了提示发生时间没有任何作用

**Comment by Ra1ny-Yuki** [comment]
经过确认，MCDR 使用的服务端消息处理器默认匹配不了不符合原版 ID 规范的玩家名称（正则表达式：`[a-zA-Z0-9_]{3,16}`），原版 ID 不应包含小数点，即：`where_is` 插件会通过 MCDR 的玩家上线事件保存玩家的在线状态，以避免对离线玩家无效的API调用，造成无端的服务端日志刷屏。而包含 `where_is` 在内的，任何需要使用 MCDR 捕获玩家相关事件的插件，均无法正常处理 `.GOODRAGE222` 这一玩家名称，因其名称包含小数点。可通过自定义[服务端处理器](https://docs.mcdreforged.com/zh-cn/latest/customize/handler.html#server-handler)，通过覆写玩家名称匹配相关属性或方法的方式，对这一玩家名称予以支持。

除此之外，即使应用了自定义处理器，MCDR的指令部分亦**可能**不支持该玩家名称（如 MCDReforged/MCDReforged#198）

如确需 MCDR 默认提供更加宽松的玩家名称匹配规则，请在 MCDR 仓库 MCDReforged/MCDReforged#258 中反馈，本仓库维护者暂无进一步处理方案，将对该 issue 予以关闭
